version: '3.4'

services:
  marsphotosoftheday.api:
    image: ${DOCKER_REGISTRY-}marsphotosofthedayapi
    build:
      context: .
      dockerfile: ../MarsPhotosOfTheDay.API/Dockerfile
    ports:
        - "8000:80"


